--------------------------------------------------------
--  DDL for Table INGREDIENTES_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B041720"."INGREDIENTES_PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER, 
	"ID_INGREDIENTE" NUMBER, 
	"CANTIDAD" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
