--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B041720"."PEDIDOS" 
   (	"ID" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"FECHA" TIMESTAMP (0), 
	"SERVIDO" NUMBER(1,0) DEFAULT 0, 
	"ID_ORDEN" NUMBER, 
	"ID_RESTAURANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
