--------------------------------------------------------
--  DDL for Table PRODUCTOSSIMILARES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B041720"."PRODUCTOSSIMILARES" 
   (	"ID_RESTAURANTE" NUMBER, 
	"ID_PROD1" NUMBER, 
	"ID_PROD2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
