--------------------------------------------------------
-- Archivo creado  - martes-octubre-24-2017   
--------------------------------------------------------
@C:\Users\dj.bautista10\Desktop\sqls\ZONAS.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTOSSIMILARES.sql
@C:\Users\dj.bautista10\Desktop\sqls\TIPOPRODUCTO.sql
@C:\Users\dj.bautista10\Desktop\sqls\CLIENTES.sql
@C:\Users\dj.bautista10\Desktop\sqls\PEDIDOS.sql
@C:\Users\dj.bautista10\Desktop\sqls\REPRESENTANTES.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTES_PRODUCTO.sql
@C:\Users\dj.bautista10\Desktop\sqls\TIPOS.sql
@C:\Users\dj.bautista10\Desktop\sqls\CLIENTESFRECUENTES.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTO_RESTAURANTE.sql
@C:\Users\dj.bautista10\Desktop\sqls\PREFERENCIAS.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTES.sql
@C:\Users\dj.bautista10\Desktop\sqls\CONDICIONESTECNICAS.sql
@C:\Users\dj.bautista10\Desktop\sqls\ORDENES.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTESSIMILARES.sql
@C:\Users\dj.bautista10\Desktop\sqls\REPRESENTA.sql
@C:\Users\dj.bautista10\Desktop\sqls\RESTAURANTES.sql
@C:\Users\dj.bautista10\Desktop\sqls\MENUS.sql
@C:\Users\dj.bautista10\Desktop\sqls\CONDICIONZONA.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTOS.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_ZONA.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_PRODSIM.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_VIDEO.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_CLIENTE.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_PEDIDO.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_REPRESENTANTES.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_INGPROD.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_TIPO.sql
@C:\Users\dj.bautista10\Desktop\sqls\NOMBREUNICO.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_CLNTFRC.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_PRODREST.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_PREFERENCIAS.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTE_PK.sql
@C:\Users\dj.bautista10\Desktop\sqls\UNICOINGREDIENTE.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_CONDICION.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_ORDEN.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_INGSIM.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_REPRESENTACION.sql
@C:\Users\dj.bautista10\Desktop\sqls\RESTUNICO.sql
@C:\Users\dj.bautista10\Desktop\sqls\VIDEOS_PK1.sql
@C:\Users\dj.bautista10\Desktop\sqls\MENUS_PK.sql
@C:\Users\dj.bautista10\Desktop\sqls\PK_CONDZONA.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTO_PK.sql
@C:\Users\dj.bautista10\Desktop\sqls\NOMBREPRODUCTO.sql
@C:\Users\dj.bautista10\Desktop\sqls\ZONAS_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTOSSIMILARES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\TIPOPRODUCTO_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\CLIENTES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\PEDIDOS_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\REPRESENTANTES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTES_PRODUCTO_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\TIPOS_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\CLIENTESFRECUENTES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTO_RESTAURANTE_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\PREFERENCIAS_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\CONDICIONESTECNICAS_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\ORDENES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\INGREDIENTESSIMILARES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\REPRESENTA_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\RESTAURANTES_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\MENUS_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\CONDICIONZONA_CONSTRAINT.sql
@C:\Users\dj.bautista10\Desktop\sqls\PRODUCTOS_CONSTRAINT.sql
