DELETE FROM PREFERENCIAS;
DELETE FROM CONDICIONZONA;
DELETE FROM REPRESENTA;
DELETE FROM PRODUCTOSSIMILARES;
DELETE FROM INGREDIENTES_PRODUCTO;
DELETE FROM TIPOPRODUCTO;
DELETE FROM INGREDIENTESSIMILARES;
DELETE FROM CLIENTESFRECUENTES;
DELETE FROM MENUS;
DELETE FROM PEDIDOS;
DELETE FROM ORDENES;
DELETE FROM PRODUCTO_RESTAURANTE; 
DELETE FROM INGREDIENTES;
DELETE FROM CLIENTES;
DELETE FROM REPRESENTANTES;
DELETE FROM PRODUCTOS;
DELETE FROM RESTAURANTES;
DELETE FROM TIPOS;
DELETE FROM ZONAS;
DELETE FROM CONDICIONESTECNICAS;


DROP TABLE "ISIS2304B121720"."CONDICIONZONA" cascade constraints;
DROP TABLE "ISIS2304B121720"."PEDIDOS" cascade constraints;
DROP TABLE "ISIS2304B121720"."REPRESENTA" cascade constraints;
DROP TABLE "ISIS2304B121720"."MENUS" cascade constraints;
DROP TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" cascade constraints;
DROP TABLE "ISIS2304B121720"."ZONAS" cascade constraints;
DROP TABLE "ISIS2304B121720"."REPRESENTANTES" cascade constraints;
DROP TABLE "ISIS2304B121720"."ORDENES" cascade constraints;
DROP TABLE "ISIS2304B121720"."TIPOS" cascade constraints;
DROP TABLE "ISIS2304B121720"."TIPOPRODUCTO" cascade constraints;
DROP TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" cascade constraints;
DROP TABLE "ISIS2304B121720"."CONDICIONESTECNICAS" cascade constraints;
DROP TABLE "ISIS2304B121720"."RESTAURANTES" cascade constraints;
DROP TABLE "ISIS2304B121720"."CLIENTESFRECUENTES" cascade constraints;
DROP TABLE "ISIS2304B121720"."PRODUCTOSSIMILARES" cascade constraints;
DROP TABLE "ISIS2304B121720"."PREFERENCIAS" cascade constraints;
DROP TABLE "ISIS2304B121720"."CLIENTES" cascade constraints;
DROP TABLE "ISIS2304B121720"."PRODUCTOS" cascade constraints;
DROP TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" cascade constraints;
DROP TABLE "ISIS2304B121720"."INGREDIENTES" cascade constraints;

--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."CLIENTES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"MESA" NUMBER    
   );

--------------------------------------------------------
--  DDL for Table CLIENTESFRECUENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."CLIENTESFRECUENTES" 
   (	"ID" NUMBER, 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CONDICIONESTECNICAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."CONDICIONESTECNICAS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;

--------------------------------------------------------
--  DDL for Table CONDICIONZONA
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."CONDICIONZONA" 
   (	"ID_ZONA" NUMBER, 
	"ID_CONDICION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;

--------------------------------------------------------
--  DDL for Table INGREDIENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."INGREDIENTES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(40 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CANTIDAD_DISPONIBLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"   NO INMEMORY ;
    
  --------------------------------------------------------
--  DDL for Table INGREDIENTES_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER, 
	"ID_INGREDIENTE" NUMBER, 
	"CANTIDAD" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table INGREDIENTESSIMILARES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" 
   (	"ID_INGREDIENTE1" NUMBER, 
	"ID_INGREDIENTE2" NUMBER, 
	"ID_REST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table MENUS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."MENUS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(40 BYTE), 
	"ID_ENTRADA" NUMBER, 
	"ID_PLATOFUERTE" NUMBER, 
	"ID_POSTRE" NUMBER, 
	"ID_BEBIDA" NUMBER, 
	"ID_RESTAURANTE" NUMBER, 
	"ID_ACOMPANIAMIENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  
  
  --------------------------------------------------------
--  DDL for Table ORDENES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."ORDENES" 
   (	"ID" NUMBER, 
	"ID_CLIENTE" NUMBER,
	"COSTOTOTAL" NUMBER, 
	"FECHA" TIMESTAMP (0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."PEDIDOS" 
   (	"ID" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"FECHA" TIMESTAMP (0), 
	"SERVIDO" NUMBER(1,0) DEFAULT 0, 
	"ID_ORDEN" NUMBER, 
	"ID_RESTAURANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table PREFERENCIAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."PREFERENCIAS" 
   (	"ID_CLIENTEFRECUENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."PRODUCTOS" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CATEGORIA" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table PRODUCTO_RESTAURANTE
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" 
   (	"ID_PROD" NUMBER, 
	"ID_REST" NUMBER, 
	"PRECIO" NUMBER, 
	"COSTO_PRODUCCION" NUMBER, 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table PRODUCTOSSIMILARES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."PRODUCTOSSIMILARES" 
   (	"ID_RESTAURANTE" NUMBER, 
	"ID_PROD1" NUMBER, 
	"ID_PROD2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table REPRESENTA
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."REPRESENTA" 
   (	"ID_RESTAURANTE" NUMBER, 
	"ID_REPRESENTANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table REPRESENTANTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."REPRESENTANTES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table RESTAURANTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."RESTAURANTES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(40 BYTE), 
	"PRECIO" NVARCHAR2(255) DEFAULT 0, 
	"ID_TIPO" NUMBER, 
	"ID_ZONA" NUMBER, 
	"PAGINA_WEB" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"   NO INMEMORY ;
  
  --------------------------------------------------------
--  DDL for Table TIPOPRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."TIPOPRODUCTO" 
   (	"ID_PROD" NUMBER, 
	"ID_TIPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table TIPOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."TIPOS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Table ZONAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B121720"."ZONAS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE), 
	"ESPACIO_ABIERTO" NUMBER(1,0) DEFAULT 0, 
	"CAPACIDAD" NUMBER, 
	"INCLUYENTE" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PRODUCTO_PK" ON "ISIS2304B121720"."PRODUCTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_CONDZONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_CONDZONA" ON "ISIS2304B121720"."CONDICIONZONA" ("ID_ZONA", "ID_CONDICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index MENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."MENUS_PK" ON "ISIS2304B121720"."MENUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_REPRESENTACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_REPRESENTACION" ON "ISIS2304B121720"."REPRESENTA" ("ID_REPRESENTANTE", "ID_RESTAURANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_INGSIM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_INGSIM" ON "ISIS2304B121720"."INGREDIENTESSIMILARES" ("ID_INGREDIENTE1", "ID_INGREDIENTE2", "ID_REST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_ORDEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_ORDEN" ON "ISIS2304B121720"."ORDENES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_CONDICION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_CONDICION" ON "ISIS2304B121720"."CONDICIONESTECNICAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index INGREDIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."INGREDIENTE_PK" ON "ISIS2304B121720"."INGREDIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_PREFERENCIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_PREFERENCIAS" ON "ISIS2304B121720"."PREFERENCIAS" ("ID_CLIENTEFRECUENTE", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_PRODREST
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_PRODREST" ON "ISIS2304B121720"."PRODUCTO_RESTAURANTE" ("ID_PROD", "ID_REST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_CLNTFRC
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_CLNTFRC" ON "ISIS2304B121720"."CLIENTESFRECUENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;

  
--------------------------------------------------------
--  DDL for Index PK_TIPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_TIPO" ON "ISIS2304B121720"."TIPOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_INGPROD
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_INGPROD" ON "ISIS2304B121720"."INGREDIENTES_PRODUCTO" ("ID_PRODUCTO", "ID_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_REPRESENTANTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_REPRESENTANTES" ON "ISIS2304B121720"."REPRESENTANTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_PEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_PEDIDO" ON "ISIS2304B121720"."PEDIDOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_CLIENTE" ON "ISIS2304B121720"."CLIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
--------------------------------------------------------
--  DDL for Index PK_VIDEO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_VIDEO" ON "ISIS2304B121720"."TIPOPRODUCTO" ("ID_PROD", "ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_PRODSIM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_PRODSIM" ON "ISIS2304B121720"."PRODUCTOSSIMILARES" ("ID_PROD1", "ID_PROD2", "ID_RESTAURANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index PK_ZONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."PK_ZONA" ON "ISIS2304B121720"."ZONAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
--------------------------------------------------------
--  DDL for Index VIDEOS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."VIDEOS_PK1" ON "ISIS2304B121720"."RESTAURANTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."PRODUCTOS" ADD CONSTRAINT "NOMBREPRODUNICO" UNIQUE ("NAME")
  USING INDEX (CREATE UNIQUE INDEX "ISIS2304B121720"."NOMBREPRODUCTO" ON "ISIS2304B121720"."PRODUCTOS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" )  ENABLE;
  ALTER TABLE "ISIS2304B121720"."PRODUCTOS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTOS" ADD CONSTRAINT "CK_CATEGORIA" CHECK (CATEGORIA = 'ENTRADA' 
OR CATEGORIA = 'PLATOFUERTE' 
OR CATEGORIA = 'POSTRE'
OR CATEGORIA = 'BEBIDA'
OR CATEGORIA = 'ACOMPAÑAMIENTO'
    ) ENABLE;
  ALTER TABLE "ISIS2304B121720"."PRODUCTOS" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTOS" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."PRODUCTOS" MODIFY ("ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  Constraints for Table CONDICIONZONA
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."CONDICIONZONA" ADD CONSTRAINT "PK_CONDZONA" PRIMARY KEY ("ID_ZONA", "ID_CONDICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."CONDICIONZONA" MODIFY ("ID_CONDICION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."CONDICIONZONA" MODIFY ("ID_ZONA" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  Constraints for Table MENUS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."MENUS" ADD CONSTRAINT "MENUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."MENUS" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."MENUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."MENUS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."MENUS" ADD CONSTRAINT "NOMBRE_NO_VACIO" CHECK (NAME !=  ' ') ENABLE;
  
  --------------------------------------------------------
--  Constraints for Table RESTAURANTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" MODIFY ("ID_ZONA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" MODIFY ("ID_TIPO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" ADD CONSTRAINT "RES_PRECIO1" CHECK (PRECIO > 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" ADD CONSTRAINT "NOMBRE_NO_VACIO1" CHECK (NAME !=  ' ') ENABLE;
  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" ADD CONSTRAINT "RESTAURANTE_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "ISIS2304B121720"."VIDEOS_PK1" ON "ISIS2304B121720"."RESTAURANTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" )  ENABLE;
  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."RESTAURANTES" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table REPRESENTA
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."REPRESENTA" MODIFY ("ID_REPRESENTANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."REPRESENTA" ADD CONSTRAINT "PK_REPRESENTACION" PRIMARY KEY ("ID_REPRESENTANTE", "ID_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."REPRESENTA" ADD CONSTRAINT "RESTUNICO" UNIQUE ("ID_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."REPRESENTA" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table INGREDIENTESSIMILARES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" ADD CONSTRAINT "INGREDIENTESSIMILARES_CHK1" CHECK (ID_INGREDIENTE1 != ID_INGREDIENTE2) ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" ADD CONSTRAINT "PK_INGSIM" PRIMARY KEY ("ID_INGREDIENTE1", "ID_INGREDIENTE2", "ID_REST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" MODIFY ("ID_INGREDIENTE2" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" MODIFY ("ID_INGREDIENTE1" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTESSIMILARES" MODIFY ("ID_REST" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table ORDENES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."ORDENES" ADD CONSTRAINT "PK_ORDEN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."ORDENES" ADD CONSTRAINT "COSTPOSITIVO" CHECK (COSTOTOTAL > 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."ORDENES" MODIFY ("COSTOTOTAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."ORDENES" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."ORDENES" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table CONDICIONESTECNICAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."CONDICIONESTECNICAS" ADD CONSTRAINT "PK_CONDICION" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."CONDICIONESTECNICAS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."CONDICIONESTECNICAS" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table INGREDIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" ADD CONSTRAINT "CK_CANTIDADDISP" CHECK (CANTIDAD_DISPONIBLE >= 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" ADD CONSTRAINT "NOMBRE_NO_VACIO2" CHECK (NAME !=  ' ') ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" ADD CONSTRAINT "INGREDIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" MODIFY ("CANTIDAD_DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES" ADD CONSTRAINT "UNICOINGREDIENTE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;

  --------------------------------------------------------
--  Constraints for Table PREFERENCIAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."PREFERENCIAS" ADD CONSTRAINT "PK_PREFERENCIAS" PRIMARY KEY ("ID_CLIENTEFRECUENTE", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."PREFERENCIAS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PREFERENCIAS" MODIFY ("ID_CLIENTEFRECUENTE" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table PRODUCTO_RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" ADD CONSTRAINT "PK_PRODREST" PRIMARY KEY ("ID_PROD", "ID_REST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" MODIFY ("COSTO_PRODUCCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" MODIFY ("ID_REST" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTO_RESTAURANTE" MODIFY ("ID_PROD" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table CLIENTESFRECUENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."CLIENTESFRECUENTES" ADD CONSTRAINT "PK_CLNTFRC" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."CLIENTESFRECUENTES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."CLIENTESFRECUENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."CLIENTESFRECUENTES" ADD CONSTRAINT "PASSCFNOTEMPY" CHECK (PASSWORD != ' ') ENABLE;


  --------------------------------------------------------
--  Constraints for Table TIPOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."TIPOS" ADD CONSTRAINT "NOMBREUNICO" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."TIPOS" ADD CONSTRAINT "PK_TIPO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."TIPOS" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table INGREDIENTES_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" ADD CONSTRAINT "CK_CANTIDAD" CHECK (CANTIDAD > 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" ADD CONSTRAINT "PK_INGPROD" PRIMARY KEY ("ID_PRODUCTO", "ID_INGREDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" MODIFY ("ID_INGREDIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."INGREDIENTES_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table REPRESENTANTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."REPRESENTANTES" ADD CONSTRAINT "PK_REPRESENTANTES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."REPRESENTANTES" ADD CONSTRAINT "PASSREPRENOTEMPTY" CHECK (PASSWORD != ' ') ENABLE;
  ALTER TABLE "ISIS2304B121720"."REPRESENTANTES" ADD CONSTRAINT "NAMEREPRENOTEMPTY" CHECK (NAME != ' ') ENABLE;
  ALTER TABLE "ISIS2304B121720"."REPRESENTANTES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."REPRESENTANTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."REPRESENTANTES" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" ADD CONSTRAINT "PK_PEDIDO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("SERVIDO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" ADD CONSTRAINT "BOOL_DESPACHADO" CHECK (SERVIDO = 1 OR SERVIDO = 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."PEDIDOS" MODIFY ("ID_ORDEN" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."CLIENTES" ADD CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."CLIENTES" ADD CONSTRAINT "NAMECLNOTEMPTY" CHECK (NAME != ' ') ENABLE;
  ALTER TABLE "ISIS2304B121720"."CLIENTES" MODIFY ("MESA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."CLIENTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."CLIENTES" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table TIPOPRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."TIPOPRODUCTO" ADD CONSTRAINT "PK_VIDEO" PRIMARY KEY ("ID_PROD", "ID_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."TIPOPRODUCTO" MODIFY ("ID_TIPO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."TIPOPRODUCTO" MODIFY ("ID_PROD" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table PRODUCTOSSIMILARES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."PRODUCTOSSIMILARES" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTOSSIMILARES" ADD CONSTRAINT "PK_PRODSIM" PRIMARY KEY ("ID_PROD1", "ID_PROD2", "ID_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."PRODUCTOSSIMILARES" MODIFY ("ID_PROD2" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."PRODUCTOSSIMILARES" MODIFY ("ID_PROD1" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table ZONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B121720"."ZONAS" ADD CONSTRAINT "PK_ZONA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B121720"."ZONAS" ADD CONSTRAINT "BOOL_INCLUYENTE" CHECK (INCLUYENTE = 1 OR INCLUYENTE = 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."ZONAS" ADD CONSTRAINT "BOOL_ESPACIOABIERTO" CHECK (ESPACIO_ABIERTO = 1 OR ESPACIO_ABIERTO = 0) ENABLE;
  ALTER TABLE "ISIS2304B121720"."ZONAS" MODIFY ("INCLUYENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."ZONAS" MODIFY ("CAPACIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."ZONAS" MODIFY ("ESPACIO_ABIERTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."ZONAS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B121720"."ZONAS" MODIFY ("ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  DDL for Index NOMBREPRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."NOMBREPRODUCTO" ON "ISIS2304B121720"."PRODUCTOS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index NOMBREUNICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."NOMBREUNICO" ON "ISIS2304B121720"."TIPOS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index RESTUNICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."RESTUNICO" ON "ISIS2304B121720"."REPRESENTA" ("ID_RESTAURANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
  --------------------------------------------------------
--  DDL for Index UNICOINGREDIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B121720"."UNICOINGREDIENTE" ON "ISIS2304B121720"."INGREDIENTES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
  
--------------------------------------------------------
--  FOREGN KEYS CONSTRAINTS
--------------------------------------------------------
  
  
  ALTER TABLE RESTAURANTES ADD (
CONSTRAINT RESTAURANTE_PK PRIMARY KEY (ID));

ALTER TABLE PRODUCTO_RESTAURANTE ADD(
CONSTRAINT FK_PRODREST FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID),
CONSTRAINT FK_RESTPROD FOREIGN KEY (ID_REST) REFERENCES RESTAURANTES(ID))
;


ALTER TABLE PRODUCTOSSIMILARES ADD(
CONSTRAINT FK_PROD1 FOREIGN KEY (ID_PROD1) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD),
CONSTRAINT FK_PROD2 FOREIGN KEY (ID_PROD2) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD))
;

ALTER TABLE PRODUCTOSSIMILARES ADD(
CONSTRAINT FK_PROD1 FOREIGN KEY (ID_PROD1, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST),
CONSTRAINT FK_PROD2 FOREIGN KEY (ID_PROD2, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST))
;

ALTER TABLE RESTAURANTES ADD(
CONSTRAINT FK_ZONAREST FOREIGN KEY (ID_ZONA) REFERENCES ZONAS(ID))
;

ALTER TABLE RESTAURANTES ADD(
CONSTRAINT FK_TIPORESTAURANTE FOREIGN KEY (ID_TIPO) REFERENCES TIPOS(ID))
;

ALTER TABLE TIPOPRODUCTO ADD(
CONSTRAINT FK_TIPOPRODC FOREIGN KEY (ID_TIPO) REFERENCES TIPOS(ID),
CONSTRAINT FK_PRODC FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID))
;

ALTER TABLE REPRESENTA ADD(
CONSTRAINT FK_REPRESENTANTE FOREIGN KEY (ID_REPRESENTANTE) REFERENCES REPRESENTANTES(ID),
CONSTRAINT FK_REPRESENTADO FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID))
;

ALTER TABLE PREFERENCIAS ADD(
CONSTRAINT FK_CLIENTEPRE FOREIGN KEY (ID_CLIENTEFRECUENTE) REFERENCES CLIENTESFRECUENTES(ID),
CONSTRAINT FK_PRODUCTOPREFERIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID))
;

ALTER TABLE MENUS ADD(
CONSTRAINT FK_BEBIDAMENU FOREIGN KEY (ID_BEBIDA, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST),
CONSTRAINT FK_ACOMPANIAMIENTOMENU FOREIGN KEY (ID_ACOMPANIAMIENTO, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST),
CONSTRAINT FK_ENTRADAMENU FOREIGN KEY (ID_ENTRADA, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST),
CONSTRAINT FK_PLATOFUERTEMENU FOREIGN KEY (ID_PLATOFUERTE, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST),
CONSTRAINT FK_POSTREMENU FOREIGN KEY (ID_POSTRE, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST)
)
;

ALTER TABLE INGREDIENTESSIMILARES ADD(
CONSTRAINT FK_RESTING FOREIGN KEY (ID_REST) REFERENCES RESTAURANTES(ID),
CONSTRAINT FK_SING1 FOREIGN KEY (ID_INGREDIENTE1) REFERENCES INGREDIENTES(ID),
CONSTRAINT FK_SING2 FOREIGN KEY (ID_INGREDIENTE2) REFERENCES INGREDIENTES(ID)
)
;

ALTER TABLE INGREDIENTES_PRODUCTO ADD(
CONSTRAINT FK_INGREDIENTE FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID),
CONSTRAINT FK_PRODUCTOING FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
)
;

ALTER TABLE CONDICIONZONA ADD(
CONSTRAINT FK_CONDICIONDELAZONA FOREIGN KEY (ID_CONDICION) REFERENCES CONDICIONESTECNICAS(ID),
CONSTRAINT FK_ZONACONDICIONADA FOREIGN KEY (ID_ZONA) REFERENCES ZONAS(ID)
)
;

ALTER TABLE CLIENTESFRECUENTES ADD(
CONSTRAINT FK_CLIENTEFR FOREIGN KEY (ID) REFERENCES CLIENTES(ID)
)
;

ALTER TABLE PEDIDOS ADD(
CONSTRAINT FK_CLIENTEPEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
CONSTRAINT FK_ORDENPEDIDO FOREIGN KEY (ID_ORDEN) REFERENCES ORDENES(ID),
CONSTRAINT FK_PRODUCTOPEDIDO FOREIGN KEY (ID_PRODUCTO, ID_RESTAURANTE) REFERENCES PRODUCTO_RESTAURANTE(ID_PROD, ID_REST),
CONSTRAINT FK_RESTAURANTEPEDIDO FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID)
)
;

ALTER TABLE ORDENES ADD(
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
)
;
ALTER TABLE ORDENES MODIFY(ID_CLIENTE NOT NULL ENABLE);
