--------------------------------------------------------
--  Constraints for Table CLIENTESFRECUENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."CLIENTESFRECUENTES" ADD CONSTRAINT "PK_CLNTFRC" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."CLIENTESFRECUENTES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."CLIENTESFRECUENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."CLIENTESFRECUENTES" ADD CONSTRAINT "PASSCFNOTEMPY" CHECK (PASSWORD != ' ') ENABLE;
