--------------------------------------------------------
--  Constraints for Table CONDICIONZONA
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."CONDICIONZONA" ADD CONSTRAINT "PK_CONDZONA" PRIMARY KEY ("ID_ZONA", "ID_CONDICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."CONDICIONZONA" MODIFY ("ID_CONDICION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."CONDICIONZONA" MODIFY ("ID_ZONA" NOT NULL ENABLE);
