--------------------------------------------------------
--  Constraints for Table INGREDIENTES_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."INGREDIENTES_PRODUCTO" ADD CONSTRAINT "CK_CANTIDAD" CHECK (CANTIDAD > 0) ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES_PRODUCTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES_PRODUCTO" ADD CONSTRAINT "PK_INGPROD" PRIMARY KEY ("ID_PRODUCTO", "ID_INGREDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES_PRODUCTO" MODIFY ("ID_INGREDIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
