--------------------------------------------------------
--  Constraints for Table INGREDIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" ADD CONSTRAINT "CK_CANTIDADDISP" CHECK (CANTIDAD_DISPONIBLE >= 0) ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" ADD CONSTRAINT "NOMBRE_NO_VACIO2" CHECK (NAME !=  ' ') ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" ADD CONSTRAINT "INGREDIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" MODIFY ("CANTIDAD_DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTES" ADD CONSTRAINT "UNICOINGREDIENTE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
