--------------------------------------------------------
--  Constraints for Table INGREDIENTESSIMILARES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."INGREDIENTESSIMILARES" ADD CONSTRAINT "INGREDIENTESSIMILARES_CHK1" CHECK (ID_INGREDIENTE1 != ID_INGREDIENTE2) ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTESSIMILARES" ADD CONSTRAINT "PK_INGSIM" PRIMARY KEY ("ID_INGREDIENTE1", "ID_INGREDIENTE2", "ID_REST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."INGREDIENTESSIMILARES" MODIFY ("ID_INGREDIENTE2" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTESSIMILARES" MODIFY ("ID_INGREDIENTE1" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."INGREDIENTESSIMILARES" MODIFY ("ID_REST" NOT NULL ENABLE);
