--------------------------------------------------------
--  Constraints for Table MENUS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."MENUS" ADD CONSTRAINT "MENUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."MENUS" MODIFY ("ID_ACOMPANIAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."MENUS" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."MENUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."MENUS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."MENUS" ADD CONSTRAINT "NOMBRE_NO_VACIO" CHECK (NAME !=  ' ') ENABLE;
