--------------------------------------------------------
--  Constraints for Table PRODUCTO_RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."PRODUCTO_RESTAURANTE" ADD CONSTRAINT "PK_PRODREST" PRIMARY KEY ("ID_PROD", "ID_REST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."PRODUCTO_RESTAURANTE" MODIFY ("COSTO_PRODUCCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTO_RESTAURANTE" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTO_RESTAURANTE" MODIFY ("ID_REST" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTO_RESTAURANTE" MODIFY ("ID_PROD" NOT NULL ENABLE);
