--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."PRODUCTOS" ADD CONSTRAINT "NOMBREPRODUNICO" UNIQUE ("NAME")
  USING INDEX (CREATE UNIQUE INDEX "ISIS2304B041720"."NOMBREPRODUCTO" ON "ISIS2304B041720"."PRODUCTOS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" )  ENABLE;
  ALTER TABLE "ISIS2304B041720"."PRODUCTOS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTOS" ADD CONSTRAINT "CK_CATEGORIA" CHECK (CATEGORIA = 'ENTRADA' 
OR CATEGORIA = 'PLATOFUERTE' 
OR CATEGORIA = 'POSTRE'
OR CATEGORIA = 'BEBIDA'
OR CATEGORIA = 'ACOMPAÑAMIENTO'
    ) ENABLE;
  ALTER TABLE "ISIS2304B041720"."PRODUCTOS" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTOS" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."PRODUCTOS" MODIFY ("ID" NOT NULL ENABLE);
