--------------------------------------------------------
--  Constraints for Table PRODUCTOSSIMILARES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."PRODUCTOSSIMILARES" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTOSSIMILARES" ADD CONSTRAINT "PK_PRODSIM" PRIMARY KEY ("ID_PROD1", "ID_PROD2", "ID_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."PRODUCTOSSIMILARES" MODIFY ("ID_PROD2" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."PRODUCTOSSIMILARES" MODIFY ("ID_PROD1" NOT NULL ENABLE);
