--------------------------------------------------------
--  Constraints for Table REPRESENTANTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."REPRESENTANTES" ADD CONSTRAINT "PK_REPRESENTANTES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."REPRESENTANTES" ADD CONSTRAINT "PASSREPRENOTEMPTY" CHECK (PASSWORD != ' ') ENABLE;
  ALTER TABLE "ISIS2304B041720"."REPRESENTANTES" ADD CONSTRAINT "NAMEREPRENOTEMPTY" CHECK (NAME != ' ') ENABLE;
  ALTER TABLE "ISIS2304B041720"."REPRESENTANTES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."REPRESENTANTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."REPRESENTANTES" MODIFY ("ID" NOT NULL ENABLE);
