--------------------------------------------------------
--  Constraints for Table ZONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B041720"."ZONAS" ADD CONSTRAINT "PK_ZONA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B041720"."ZONAS" ADD CONSTRAINT "BOOL_INCLUYENTE" CHECK (INCLUYENTE = 1 OR INCLUYENTE = 0) ENABLE;
  ALTER TABLE "ISIS2304B041720"."ZONAS" ADD CONSTRAINT "BOOL_ESPACIOABIERTO" CHECK (ESPACIO_ABIERTO = 1 OR ESPACIO_ABIERTO = 0) ENABLE;
  ALTER TABLE "ISIS2304B041720"."ZONAS" MODIFY ("INCLUYENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."ZONAS" MODIFY ("CAPACIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."ZONAS" MODIFY ("ESPACIO_ABIERTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."ZONAS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B041720"."ZONAS" MODIFY ("ID" NOT NULL ENABLE);
